### ISSUE TITLE
traced color?

### ISSUE THREAD

**Issue by rahmirtrt** [nullmastermind/inkscape-for-trace#5]
inkscape.exe --actions="select-all;selection-trace:256,false,true,true,4,1.0,0.20;export-filename:output.svg;export-do;" "input.png" --batch-process
I use this command and it works fine.

outline How do I color traced lines? like fill:#0000ff.

**Comment by nullmastermind** [comment]
This issue is not within my support scope. I only support adding more options for tracing in the command line. For other issues, they are more related to Inkscape, so you should seek help there.
